app1/urls.py
from django.urls import path
from app1.views import *
app_name='app1'
urlpatterns=[
    path('prasad/',prasad,name='prasad'),
    path('ram/',ram,name='ram'),
]

app2/urls.py
from django.urls import path
from app2.views import *
app_name='app2'
urlpatterns=[
    path('eswar/',eswar,name='eswar'),
    path('laxman/',laxman,name='laxman'),
]

project13/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
    
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def prasad(request):
    return render(request,'prasad.html')


def ram(request):
    return render(request,'ram.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def eswar(request):
    return render(request,'eswar.html')


def laxman(request):
    return render(request,'laxman.html')    

templates/eswar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        body
         {
            background-color: rgb(0, 255, 213);

         }
         h1
         {
            color: blue;
         }
    </style>
</head>
<body>
    <center>
        <h1>WELCOME TO ESWAR HTML PAGE</h1>
        <a href="{% url 'app1:ram' %}"> <h3> go to ram html page </h3></a><br>
        <a href="{% url 'app1:prasad' %}"><h3>  go to prasad html page</h3></a><br>
        <a href="{% url 'app2:laxman' %}"><h3>  go to laxman html page </h3></a>
        
        
    </center>
    
</body>
</html>

templates/laxman.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        body

        {
            background-color: darksalmon;
        }
        h1
        {
            color: aqua;
        }
        
    </style>
    </body>
</head>
<body style="background-color:darkgreen;">
    <center> 
        <h1> WELCOME TO LAXMAN HTML PAGE</h1>
        <a href="{% url 'app1:ram' %}"> <h3 style="color:blue;"> go to ram html page </h3></a><br>
        <a href="{% url 'app1:prasad' %}"><h3>  go to prasad html page</h3></a><br>
        <a href="{% url 'app2:eswar' %}"><h3>  go to eswar html page </h3></a>
        
    </center>
    
</body>
</html>

templates/prasad.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        body
        {
        background-color:burlywood;
        }
        h1
        {
            color: rgb(236, 8, 206);
        }
    </style>
</head>
<body>
    <center>
        <h1>WELCOME TO PRASAD HTML PAGE </h1>
        <a href="{% url 'app1:ram' %}">  <h3>go to ram html page</h3></a><br>
        <a href="{% url 'app2:eswar' %}"> <h3 >go to eswar html page </h3></a><br>
        <a href="{% url 'app2:laxman' %}">  <h3>go to laxman html page</h3></a>

    </center>
    
</body>
</html>

templates/ram.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        body
        {
            background-color: brown;
        }
        h1{

            color: black;
        }
        h3
        {
            color: chartreuse;
        }
    </style>
</head>
<body>
    <center> 
        <h1>WELCOME TO RAM HTML PAGE</h1>
        <a href="{% url 'app2:eswar' %}"> <h3>go to ram html page </h3></a><br>
        <a href="{% url 'app1:prasad' %}"><h3>  go to prasad html page</h3></a><br>
        <a href="{% url 'app2:laxman' %}"><h3>  go to laxman html page </h3></a>
    </center>
    
</body>
</html>